Repository wecode-bootcamp-korea/17-1st-WeGotDiz-backend, pull requests merged in 2021-02, with the labels that each got.

#2 MODIFY: class User, Product, Category, Order
  product/models.py
  purchase/models.py
  requirements.txt
  user/models.py
  user/views.py
Labels: Status: Accepted

#3 [17기 허민지] MODIFY: SignUpView, ADD: validators.py
  WeGotDiz/urls.py
  user/urls.py
  user/validators.py
  user/views.py
Labels: Status: 리뷰 진행중

#5 [17기 허민지] MODIFY: feature/signin MERGED FILES
  WeGotDiz/urls.py
  user/urls.py
  user/utils.py
  user/validators.py
  user/views.py
Labels: Status: Accepted

#6 [17기 이동근]ADD: categoryproduct View
  .idea/.gitignore
  .idea/17-1st-WeGotDiz-backend.iml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  WeGotDiz/settings.py
  WeGotDiz/urls.py
  community/migrations/0001_initial.py
  db_uploader.py
  product/migrations/0001_initial.py
  product/models.py
  product/urls.py
  product/views.py
  purchase/migrations/0001_initial.py
  user/migrations/0001_initial.py
  user/views.py
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#10 [17기 이지윤] MODIFY: product app에 views.py, models.py, urls.py 수정
  .gitignore
  product/urls.py
  product/views.py
Labels: Status: 리뷰 진행중

#4 [17기 최호진] MODIFY: RewardListView product_info 추가, RewardOrderView exception 핸들링 추가, 변수명 수정
  WeGotDiz/urls.py
  community/views.py
  product/urls.py
  product/views.py
  purchase/urls.py
  purchase/views.py
  user/utils.py
Labels: Status: Accepted

#8 [17기 허민지] MODIFY: UserFundView UserLikeView, ADD: UserInfoView
  WeGotDiz/urls.py
  db_uploader.py
  product/models.py
  product/views.py
  user/models.py
  user/urls.py
  user/utils.py
  user/views.py
Labels: Status: 컨플릭트 해결 요청

#11 [17기 이지윤] MODIFY: product 앱의 views.py 수정
  product/urls.py
  product/views.py
  user/utils.py
Labels: Status: Accepted

#12 [17기 이지윤] MODIFY: migration 파일 삭제
  community/migrations/0001_initial.py
  product/migrations/0001_initial.py
  product/models.py
  product/views.py
  purchase/migrations/0001_initial.py
  purchase/views.py
  user/migrations/0001_initial.py
  user/views.py
Labels: Status: 리뷰 요청
